---
name: Text-CSV-Unicode
version: 0.05
author:
  - 'Robin Barker <rmbarker@cpan.org>'
abstract: |-
  comma-separated values manipulation routines
                          with potentially wide character data
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Text::CSV: 0.01
  perl: 5.008
provides:
  Text::CSV::Unicode:
    file: lib/Text/CSV/Unicode.pm
    version: 0.05
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
