---
name: Text-CSV-Unicode
version: 0.112
author:
  - 'Robin Barker <rmbarker@cpan.org>'
abstract: |-
  comma-separated values manipulation routines
  			with potentially wide character data
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  perl: 5.008
configure_requires:
  Module::Build: 0.35
provides:
  Text::CSV::Base:
    file: lib/Text/CSV/Base.pm
    version: 0.04
  Text::CSV::Unicode:
    file: lib/Text/CSV/Unicode.pm
    version: 0.112
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
