---
abstract: "comma-separated values manipulation routines\n\t\t\twith potentially wide character data"
author:
  - 'Robin Barker <rmbarker@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-Unicode
provides:
  Text::CSV::Base:
    file: lib/Text/CSV/Base.pm
    version: 0.041
  Text::CSV::Unicode:
    file: lib/Text/CSV/Unicode.pm
    version: 0.113
requires:
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.113
